In [1]:
from __future__ import print_function
import pandas as pd
import numpy as np
from ggplot import *
import scipy.stats
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
path = "C:\\Users\\Saad Khalid\\Desktop\\IDS project\\turnstile_weather_v2.csv"
weather_subway = pd.read_csv(path)

In [3]:
weather_subway.shape

(42649, 27)

In [4]:
weather_subway

,UNIT,DATEn,TIMEn,ENTRIESn,EXITSn,ENTRIESn_hourly,EXITSn_hourly,datetime,hour,day_week,...,pressurei,rain,tempi,wspdi,meanprecipi,meanpressurei,meantempi,meanwspdi,weather_lat,weather_lon
0,R003,05-01-11,00:00:00,4388333,2911002,0,0,2011-05-01 00:00:00,0,6,...,30.22,0,55.9,3.5,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
1,R003,05-01-11,04:00:00,4388333,2911002,0,0,2011-05-01 04:00:00,4,6,...,30.25,0,52.0,3.5,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
2,R003,05-01-11,12:00:00,4388333,2911002,0,0,2011-05-01 12:00:00,12,6,...,30.28,0,62.1,6.9,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
3,R003,05-01-11,16:00:00,4388333,2911002,0,0,2011-05-01 16:00:00,16,6,...,30.26,0,57.9,15.0,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
4,R003,05-01-11,20:00:00,4388333,2911002,0,0,2011-05-01 20:00:00,20,6,...,30.28,0,52.0,10.4,0.000000,30.258000,55.980000,7.860000,40.700348,-73.887177
5,R003,05-02-11,00:00:00,4388348,2911036,15,34,2011-05-02 00:00:00,0,0,...,30.31,0,50.0,6.9,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
6,R003,05-02-11,04:00:00,5818689,3874767,19,40,2011-05-02 04:00:00,4,0,...,30.27,0,50.0,4.6,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
7,R003,05-02-11,08:00:00,4388855,2911194,488,118,2011-05-02 08:00:00,8,0,...,30.30,0,53.1,10.4,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
8,R003,05-02-11,12:00:00,4389345,2911326,490,132,2011-05-02 12:00:00,12,0,...,30.24,0,57.0,11.5,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
9,R003,05-02-11,16:00:00,4389576,2911558,231,232,2011-05-02 16:00:00,16,0,...,30.16,0,59.0,11.5,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
10,R003,05-02-11,20:00:00,4389811,2911963,235,405,2011-05-02 20:00:00,20,0,...,30.15,0,55.9,4.6,0.000000,30.238333,54.166667,8.250000,40.700348,-73.887177
11,R003,05-03-11,00:00:00,4389885,2912127,74,164,2011-05-03 00:00:00,0,1,...,30.13,0,54.0,4.6,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
12,R003,05-03-11,04:00:00,4389905,2912160,20,33,2011-05-03 04:00:00,4,1,...,30.11,0,51.8,5.8,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
13,R003,05-03-11,12:00:00,4390880,2912394,975,234,2011-05-03 12:00:00,12,1,...,30.07,0,60.8,9.2,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
14,R003,05-03-11,16:00:00,4391147,2912651,267,257,2011-05-03 16:00:00,16,1,...,29.98,0,66.0,9.2,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
15,R003,05-03-11,20:00:00,4391424,2913049,277,398,2011-05-03 20:00:00,20,1,...,29.95,0,62.1,11.5,0.000000,30.048000,58.940000,8.060000,40.700348,-73.887177
16,R003,05-04-11,00:00:00,4391507,2913223,83,174,2011-05-04 00:00:00,0,2,...,29.94,1,59.0,9.2,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
17,R003,05-04-11,04:00:00,4391531,2913258,24,35,2011-05-04 04:00:00,4,2,...,29.91,1,60.1,0.0,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
18,R003,05-04-11,08:00:00,4392063,2913388,532,130,2011-05-04 08:00:00,8,2,...,29.94,1,55.4,15.0,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
19,R003,05-04-11,12:00:00,4392517,2913495,454,107,2011-05-04 12:00:00,12,2,...,29.96,1,51.1,11.5,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
20,R003,05-04-11,16:00:00,4392764,2913744,247,249,2011-05-04 16:00:00,16,2,...,29.96,1,48.0,18.4,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
21,R003,05-04-11,20:00:00,4392984,2914100,220,356,2011-05-04 20:00:00,20,2,...,30.01,1,50.0,16.1,0.010000,29.953333,53.933333,11.700000,40.700348,-73.887177
22,R003,05-05-11,00:00:00,4393043,2914284,59,184,2011-05-05 00:00:00,0,3,...,30.01,0,48.9,16.1,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
23,R003,05-05-11,04:00:00,4393062,2914319,19,35,2011-05-05 04:00:00,4,3,...,29.98,0,48.0,12.7,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
24,R003,05-05-11,12:00:00,4394057,2914509,995,190,2011-05-05 12:00:00,12,3,...,29.91,0,60.8,15.0,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
25,R003,05-05-11,16:00:00,4394364,2914754,307,245,2011-05-05 16:00:00,16,3,...,29.88,0,63.0,19.6,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
26,R003,05-05-11,20:00:00,4394592,2915145,228,391,2011-05-05 20:00:00,20,3,...,29.94,0,57.9,12.7,0.000000,29.944000,55.720000,15.220000,40.700348,-73.887177
27,R003,05-06-11,00:00:00,4394665,2915321,73,176,2011-05-06 00:00:00,0,4,...,29.97,0,55.0,3.5,0.000000,29.918000,60.580000,11.300000,40.700348,-73.887177
28,R003,05-06-11,04:00:00,4394687,2915369,22,48,2011-05-06 04:00:00,4,4,...,29.96,0,52.0,8.1,0.000000,29.918000,60.580000,11.300000,40.700348,-73.887177
29,R003,05-06-11,12:00:00,4395657,2915590,970,221,2011-05-06 12:00:00,12,4,...,29.94,0,68.0,16.1,0.000000,29.918000,60.580000,11.300000,40.700348,-73.887177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42619,R464,05-26-11,16:00:00,419894,95280,0,0,2011-05-26 16:00:00,16,3,...,29.89,0,69.1,9.2,0.000000,29.922000,66.640000,7.160000,40.660004,-73.844849
42620,R464,05-26-11,20:00:00,419894,95280,0,0,2011-05-26 20:00:00,20,3,...,29.88,0,66.9,8.1,0.000000,29.922000,66.640000,7.160000,40.660004,-73.844849
42621,R464,05-27-11,00:00:00,419894,95280,0,0,2011-05-27 00:00:00,0,4,...,29.92,0,66.0,4.6,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42622,R464,05-27-11,04:00:00,419894,95280,0,0,2011-05-27 04:00:00,4,4,...,29.94,0,64.0,3.5,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42623,R464,05-27-11,12:00:00,419894,95280,0,0,2011-05-27 12:00:00,12,4,...,29.99,0,73.0,12.7,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42624,R464,05-27-11,16:00:00,419894,95280,0,0,2011-05-27 16:00:00,16,4,...,29.93,0,75.9,20.7,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42625,R464,05-27-11,20:00:00,419894,95280,0,0,2011-05-27 20:00:00,20,4,...,29.96,0,66.9,21.9,0.000000,29.948000,69.160000,12.680000,40.660004,-73.844849
42626,R464,05-28-11,00:00:00,419894,95280,0,0,2011-05-28 00:00:00,0,5,...,30.00,0,66.0,4.6,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42627,R464,05-28-11,04:00:00,419894,95280,0,0,2011-05-28 04:00:00,4,5,...,30.00,0,64.0,6.9,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42628,R464,05-28-11,12:00:00,419894,95280,0,0,2011-05-28 12:00:00,12,5,...,30.05,0,77.0,11.5,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42629,R464,05-28-11,16:00:00,419894,95280,0,0,2011-05-28 16:00:00,16,5,...,30.05,0,73.9,15.0,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42630,R464,05-28-11,20:00:00,419894,95280,0,0,2011-05-28 20:00:00,20,5,...,30.06,0,68.0,13.8,0.000000,30.032000,69.780000,10.360000,40.660004,-73.844849
42631,R464,05-29-11,00:00:00,419894,95280,0,0,2011-05-29 00:00:00,0,6,...,30.09,0,66.0,9.2,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42632,R464,05-29-11,04:00:00,419894,95280,0,0,2011-05-29 04:00:00,4,6,...,30.09,0,64.9,6.9,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42633,R464,05-29-11,08:00:00,129127,35492,0,0,2011-05-29 08:00:00,8,6,...,30.13,0,66.2,6.9,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42634,R464,05-29-11,12:00:00,419894,95280,0,0,2011-05-29 12:00:00,12,6,...,30.13,0,75.9,10.4,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42635,R464,05-29-11,16:00:00,419894,95280,0,0,2011-05-29 16:00:00,16,6,...,30.06,0,75.0,18.4,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42636,R464,05-29-11,20:00:00,419894,95280,0,0,2011-05-29 20:00:00,20,6,...,30.08,0,70.0,15.0,0.000000,30.096667,69.666667,11.133333,40.660004,-73.844849
42637,R464,05-30-11,00:00:00,419894,95280,0,0,2011-05-30 00:00:00,0,0,...,30.09,1,64.9,5.8,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42638,R464,05-30-11,04:00:00,419894,95280,0,0,2011-05-30 04:00:00,4,0,...,30.04,1,66.9,3.5,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42639,R464,05-30-11,08:00:00,129127,35492,0,0,2011-05-30 08:00:00,8,0,...,30.09,1,72.0,13.8,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42640,R464,05-30-11,12:00:00,419894,95280,0,0,2011-05-30 12:00:00,12,0,...,30.10,1,82.9,8.1,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42641,R464,05-30-11,16:00:00,419894,95280,0,0,2011-05-30 16:00:00,16,0,...,30.06,1,82.0,9.2,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42642,R464,05-30-11,20:00:00,419894,95280,0,0,2011-05-30 20:00:00,20,0,...,30.10,1,73.0,4.6,0.001667,30.080000,73.616667,7.500000,40.660004,-73.844849
42643,R464,05-31-11,00:00:00,419894,95280,0,0,2011-05-31 00:00:00,0,1,...,30.13,0,72.0,0.0,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42644,R464,05-31-11,04:00:00,567311,132804,0,0,2011-05-31 04:00:00,4,1,...,30.14,0,73.0,6.9,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42645,R464,05-31-11,08:00:00,290767,59788,0,0,2011-05-31 08:00:00,8,1,...,30.19,0,80.1,6.9,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42646,R464,05-31-11,12:00:00,419894,95280,0,0,2011-05-31 12:00:00,12,1,...,30.20,0,81.0,10.4,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42647,R464,05-31-11,16:00:00,419894,95280,0,0,2011-05-31 16:00:00,16,1,...,30.17,0,77.0,13.8,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849
42648,R464,05-31-11,20:00:00,419894,95280,0,0,2011-05-31 20:00:00,20,1,...,30.18,0,69.1,4.6,0.000000,30.168333,75.366667,7.100000,40.660004,-73.844849

In [5]:
ggplot(aes(x='ENTRIESn_hourly', color='rain', fill='rain'), data = weather_subway) + \
    geom_histogram(binwidth=500, alpha = 0.8) + \
    xlab("Hourly passenger entries") +\
    ylab("Frequency") + \
    ggtitle("Hourly passenger entries (with and without rain)") + \
    theme_seaborn()

C:\Users\Saad Khalid\Anaconda\lib\site-packages\pandas\util\decorators.py:53: FutureWarning: rows is deprecated, use index instead
  warnings.warn(msg, FutureWarning)
C:\Users\Saad Khalid\Anaconda\lib\site-packages\ggplot\geoms\geom_bar.py:47: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  _reset = self.bottom == None or (self.ax != None and self.ax != ax)

In [6]:
ggplot(aes(x='EXITSn_hourly', color='rain', fill='rain'), data = weather_subway) + \
    geom_histogram(binwidth=500, alpha = 0.8) + \
    xlab("Hourly passenger exits") +\
    ylab("Frequency") + \
    ggtitle("Hourly passenger exits (with and without rain)") + \
    theme_seaborn()

In [13]:
ggplot(aes(x='ENTRIESn_hourly', color='weekday', fill='weekday'), data = weather_subway) + \
    geom_histogram(alpha = 0.8, binwidth = 500) +\
    xlab("Hourly passenger entries") +\
    ylab("Frequency") +\
    ggtitle("Hourly passenger entries (weekdays and weekends)") +\
    theme_seaborn()

C:\Users\Saad Khalid\Anaconda\lib\site-packages\pandas\util\decorators.py:53: FutureWarning: rows is deprecated, use index instead
  warnings.warn(msg, FutureWarning)
C:\Users\Saad Khalid\Anaconda\lib\site-packages\ggplot\geoms\geom_bar.py:47: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  _reset = self.bottom == None or (self.ax != None and self.ax != ax)

In [6]:
ggplot(aes(x='ENTRIESn_hourly', color='weekday', fill='weekday'), data = weather_subway) + \
    geom_density() + \
    xlab("Hourly passenger entries") + \
    ylab("Frequency") + \
    ggtitle("Hourly passenger entries (weekdays and weekends)") + \
    theme_seaborn()

In [11]:
by_hour = weather_subway[['ENTRIESn_hourly', 'EXITSn_hourly']].groupby(weather_subway['hour'], as_index=False).mean()

In [12]:
ggplot(aes(x='hour', y='ENTRIESn_hourly'), data=by_hour) + \
    geom_point(alpha = 0.7) + \
    geom_line(color = 'green') + \
    theme_seaborn()

In [9]:
ggplot(aes(x='hour', y='ENTRIESn_hourly', weight = 'ENTRIESn_hourly'), data=by_hour) + \
    geom_bar(alpha = 0.5, fill='blue') + \
    geom_point () + \
    geom_line() + \
    theme_seaborn()

NameError: name 'by_hour' is not defined

In [8]:
ggplot(aes(x ='hour', y = 'ENTRIESn_hourly'), data = weather_subway) + \
    geom_point(position='jitter', alpha = 0.5) + \
    geom_smooth(size=5, color='green', alpha = 0.8) + \
    theme_seaborn()

In [7]:
ggplot(aes(x = 'day_week', y='ENTRIESn_hourly'), data=weather_subway) + \
    geom_point(alpha=1, position='jitter') + \
    geom_smooth(size = 3, color='red', alpha = 0.8) + \
    facet_wrap('rain') + \
    theme_seaborn()

In [14]:
ggplot( aes(x='tempi',y='ENTRIESn_hourly'), data=weather_subway) + \
    geom_smooth(alpha=0.5, size = 3, color = 'red') + \
    xlab("Temperature (Fahrenheit)") + \
    ylab("Hourly passenger entries") + \
    ggtitle("Relationship between temperature and ridership") + \
    theme_seaborn()

In [11]:
by_temp = weather_subway[['ENTRIESn_hourly', 'EXITSn_hourly']].groupby(weather_subway['tempi'], as_index=False).mean()
by_temp
##ggplot(aes(x='tempi', y = 'ENTRIESn_hourly'), data=by_temp) + \
##    geom_line() 
labels = [ "{0} - {1}".format(i, i + 4.9) for i in range(45, 85, 5) ]
labels
by_temp['group'] = pd.cut(by_temp.tempi, range(45, 90, 5), right=False, labels=labels)
by_temp
by_temp_group = by_temp[['ENTRIESn_hourly', 'EXITSn_hourly']].groupby(by_temp['group'], as_index=False).mean()
by_temp_group
ggplot(aes(x= range(8), y = 'ENTRIESn_hourly'), data=by_temp_group) + \
    geom_point(alpha = 0.5, size = 50) + \
    geom_line(alpha = 0.5) + \
    theme_seaborn() + \
    scale_x_discrete(breaks = range(8), labels=by_temp_group.group) +\
    xlab("Temperature ranges (Fahrenheit)") + \
    ylab("Average ridership") + \
    ggtitle("Average ridership across temperature ranges")

In [5]:
rain_model = smf.ols(formula = 'ENTRIESn_hourly ~ C(rain)', data=weather_subway).fit()
print(rain_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        ENTRIESn_hourly   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     28.46
Date:                Fri, 15 May 2015   Prob (F-statistic):           9.61e-08
Time:                        12:45:32   Log-Likelihood:            -4.0128e+05
No. Observations:               42649   AIC:                         8.026e+05
Df Residuals:                   42647   BIC:                         8.026e+05
Df Model:                           1
================================================================================
                   coef    std err          t      P>|t|      [95.0% Conf. Int.]
--------------------------------------------------------------------------------
Intercept     1845.5394     16.231    113.702      0.000      1813.726  1877.353
C(rain)[T.1]   182.6566     34.238      5.335      0.000       115.549   249.765
==============================================================================
Omnibus:                    36029.930   Durbin-Watson:                   0.918
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1070292.326
Skew:                           4.023   Prob(JB):                         0.00
Kurtosis:                      26.185   Cond. No.                         2.54
==============================================================================

In [14]:
rain_model = smf.ols(formula = 'ENTRIESn_hourly ~ C(weekday) +  C(hour) + C(UNIT)+tempi + C(rain)', data=weather_subway).fit()
print(rain_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        ENTRIESn_hourly   R-squared:                       0.542
Model:                            OLS   Adj. R-squared:                  0.539
Method:                 Least Squares   F-statistic:                     203.0
Date:                Tue, 12 May 2015   Prob (F-statistic):               0.00
Time:                        14:02:06   Log-Likelihood:            -3.8465e+05
No. Observations:               42649   AIC:                         7.698e+05
Df Residuals:                   42401   BIC:                         7.720e+05
Df Model:                         247
===================================================================================
                      coef    std err          t      P>|t|      [95.0% Conf. Int.]
-----------------------------------------------------------------------------------
Intercept        -224.4336    176.181     -1.274      0.203      -569.752   120.885
C(weekday)[T.1]  1010.1674     21.697     46.557      0.000       967.640  1052.694
C(hour)[T.4]    -1109.1845     33.047    -33.564      0.000     -1173.957 -1044.412
C(hour)[T.8]     -788.4614     35.139    -22.438      0.000      -857.335  -719.587
C(hour)[T.12]    1707.3373     34.675     49.238      0.000      1639.373  1775.302
C(hour)[T.16]     997.4998     34.643     28.794      0.000       929.599  1065.400
C(hour)[T.20]    1856.7050     33.232     55.872      0.000      1791.571  1921.840
C(UNIT)[T.R004]   365.2646    216.492      1.687      0.092       -59.064   789.593
C(UNIT)[T.R005]   350.3608    217.417      1.611      0.107       -75.780   776.502
C(UNIT)[T.R006]   534.7210    215.024      2.487      0.013       113.270   956.172
C(UNIT)[T.R007]   169.2553    218.044      0.776      0.438      -258.115   596.626
C(UNIT)[T.R008]   161.8474    218.365      0.741      0.459      -266.152   589.847
C(UNIT)[T.R009]   163.2429    216.493      0.754      0.451      -261.087   587.573
C(UNIT)[T.R011]  7256.4844    213.893     33.926      0.000      6837.249  7675.720
C(UNIT)[T.R012]  8610.7014    213.346     40.360      0.000      8192.538  9028.865
C(UNIT)[T.R013]  2509.1423    213.346     11.761      0.000      2090.979  2927.305
C(UNIT)[T.R016]   687.0441    213.893      3.212      0.001       267.809  1106.280
C(UNIT)[T.R017]  4124.1369    213.346     19.331      0.000      3705.974  4542.300
C(UNIT)[T.R018]  7697.4444    213.615     36.034      0.000      7278.755  8116.134
C(UNIT)[T.R019]  3160.9366    213.343     14.816      0.000      2742.780  3579.094
C(UNIT)[T.R020]  6300.2337    213.346     29.531      0.000      5882.071  6718.397
C(UNIT)[T.R021]  4610.9364    213.894     21.557      0.000      4191.701  5030.172
C(UNIT)[T.R022]  9444.6262    213.346     44.269      0.000      9026.463  9862.789
C(UNIT)[T.R023]  6079.8036    213.346     28.497      0.000      5661.640  6497.967
C(UNIT)[T.R024]  3122.1506    213.615     14.616      0.000      2703.460  3540.841
C(UNIT)[T.R025]  5257.8291    213.343     24.645      0.000      4839.672  5675.986
C(UNIT)[T.R027]  2894.2391    213.346     13.566      0.000      2476.076  3312.402
C(UNIT)[T.R029]  7156.2122    213.346     33.543      0.000      6738.049  7574.375
C(UNIT)[T.R030]  3026.4057    213.346     14.185      0.000      2608.243  3444.569
C(UNIT)[T.R031]  4278.1746    213.346     20.053      0.000      3860.011  4696.338
C(UNIT)[T.R032]  4372.3662    213.619     20.468      0.000      3953.669  4791.063
C(UNIT)[T.R033]  8161.1853    213.346     38.253      0.000      7743.022  8579.348
C(UNIT)[T.R034]  1041.7561    218.047      4.778      0.000       614.380  1469.133
C(UNIT)[T.R035]  2721.4017    213.893     12.723      0.000      2302.167  3140.637
C(UNIT)[T.R036]   640.4419    215.892      2.966      0.003       217.289  1063.595
C(UNIT)[T.R037]   765.1139    214.169      3.572      0.000       345.339  1184.889
C(UNIT)[T.R038]   107.3066    216.494      0.496      0.620      -317.025   531.638
C(UNIT)[T.R039]   638.5904    219.348      2.911      0.004       208.665  1068.516
C(UNIT)[T.R040]  1167.8233    213.890      5.460      0.000       748.595  1587.051
C(UNIT)[T.R041]  3026.2176    213.346     14.185      0.000      2608.054  3444.381
C(UNIT)[T.R042]   507.4598    215.020      2.360      0.018        86.016   928.904
C(UNIT)[T.R043]  2813.3520    213.346     13.187      0.000      2395.189  3231.515
C(UNIT)[T.R044]  4604.7606    213.346     21.583      0.000      4186.597  5022.924
C(UNIT)[T.R046]  8271.2122    213.346     38.769      0.000      7853.049  8689.375
C(UNIT)[T.R049]  2699.0240    213.346     12.651      0.000      2280.861  3117.187
C(UNIT)[T.R050]  3954.9152    213.896     18.490      0.000      3535.676  4374.155
C(UNIT)[T.R051]  5060.7660    213.346     23.721      0.000      4642.603  5478.929
C(UNIT)[T.R052]  1114.9135    217.413      5.128      0.000       688.779  1541.048
C(UNIT)[T.R053]  3091.2583    213.889     14.453      0.000      2672.031  3510.486
C(UNIT)[T.R054]  1385.0737    213.893      6.476      0.000       965.838  1804.309
C(UNIT)[T.R055]  8258.4583    213.343     38.710      0.000      7840.302  8676.614
C(UNIT)[T.R056]  1369.5496    213.893      6.403      0.000       950.314  1788.785
C(UNIT)[T.R057]  4809.1531    213.346     22.542      0.000      4390.990  5227.316
C(UNIT)[T.R058]   568.0516    213.619      2.659      0.008       149.354   986.749
C(UNIT)[T.R059]  1107.1051    215.898      5.128      0.000       683.941  1530.269
C(UNIT)[T.R060]   713.9769    215.021      3.321      0.001       292.532  1135.422
C(UNIT)[T.R061]   509.0515    219.020      2.324      0.020        79.769   938.334
C(UNIT)[T.R062]  2663.0133    213.346     12.482      0.000      2244.850  3081.176
C(UNIT)[T.R063]  1045.2667    218.692      4.780      0.000       616.626  1473.907
C(UNIT)[T.R064]   755.1562    216.195      3.493      0.000       331.409  1178.903
C(UNIT)[T.R065]   753.1174    217.417      3.464      0.001       326.975  1179.260
C(UNIT)[T.R066]   148.2229    218.048      0.680      0.497      -279.156   575.602
C(UNIT)[T.R067]   760.2453    219.015      3.471      0.001       330.972  1189.519
C(UNIT)[T.R068]   360.9372    219.015      1.648      0.099       -68.337   790.211
C(UNIT)[T.R069]   846.8550    217.103      3.901      0.000       421.328  1272.382
C(UNIT)[T.R070]  1713.9918    213.346      8.034      0.000      1295.829  2132.155
C(UNIT)[T.R080]  3538.3197    213.346     16.585      0.000      3120.157  3956.483
C(UNIT)[T.R081]  3488.3372    213.896     16.309      0.000      3069.098  3907.577
C(UNIT)[T.R082]  1428.6870    213.893      6.679      0.000      1009.452  1847.922
C(UNIT)[T.R083]  3052.7283    213.346     14.309      0.000      2634.565  3470.891
C(UNIT)[T.R084]  9957.0025    213.346     46.671      0.000      9538.839  1.04e+04
C(UNIT)[T.R085]  2537.2987    213.896     11.862      0.000      2118.059  2956.538
C(UNIT)[T.R086]  2526.3197    213.346     11.841      0.000      2108.157  2944.483
C(UNIT)[T.R087]  1150.7905    214.451      5.366      0.000       730.461  1571.120
C(UNIT)[T.R089]   440.8322    213.893      2.061      0.039        21.597   860.068
C(UNIT)[T.R090]   331.1488    219.016      1.512      0.131       -98.127   760.425
C(UNIT)[T.R091]  1042.5552    218.046      4.781      0.000       615.181  1469.930
C(UNIT)[T.R092]  1917.5882    216.194      8.870      0.000      1493.844  2341.332
C(UNIT)[T.R093]  1949.4690    216.799      8.992      0.000      1524.539  2374.399
C(UNIT)[T.R094]  1692.0954    213.890      7.911      0.000      1272.867  2111.324
C(UNIT)[T.R095]  2099.5755    214.732      9.778      0.000      1678.697  2520.454
C(UNIT)[T.R096]  2285.7430    213.615     10.700      0.000      1867.053  2704.433
C(UNIT)[T.R097]  2906.4823    213.615     13.606      0.000      2487.793  3325.171
C(UNIT)[T.R098]  1760.8789    213.346      8.254      0.000      1342.716  2179.042
C(UNIT)[T.R099]  2317.9057    213.346     10.865      0.000      1899.743  2736.069
C(UNIT)[T.R100]   491.9127    214.451      2.294      0.022        71.585   912.240
C(UNIT)[T.R101]  2752.2982    213.346     12.901      0.000      2334.135  3170.461
C(UNIT)[T.R102]  3641.1369    213.346     17.067      0.000      3222.974  4059.300
C(UNIT)[T.R103]  1319.8825    217.415      6.071      0.000       893.745  1746.020
C(UNIT)[T.R104]  1280.9098    213.890      5.989      0.000       861.682  1700.138
C(UNIT)[T.R105]  3290.8359    213.346     15.425      0.000      2872.673  3708.999
C(UNIT)[T.R106]   985.1048    219.015      4.498      0.000       555.830  1414.379
C(UNIT)[T.R107]   396.4057    219.346      1.807      0.071       -33.517   826.328
C(UNIT)[T.R108]  5180.0025    213.346     24.280      0.000      4761.839  5598.166
C(UNIT)[T.R111]  3177.1262    213.346     14.892      0.000      2758.963  3595.289
C(UNIT)[T.R112]  1627.4295    213.615      7.619      0.000      1208.740  2046.119
C(UNIT)[T.R114]   836.7274    213.617      3.917      0.000       418.034  1255.421
C(UNIT)[T.R115]  1208.4259    213.343      5.664      0.000       790.269  1626.583
C(UNIT)[T.R116]  3156.2713    213.346     14.794      0.000      2738.108  3574.434
C(UNIT)[T.R117]   804.1172    218.688      3.677      0.000       375.485  1232.750
C(UNIT)[T.R119]  1794.8584    215.305      8.336      0.000      1372.855  2216.861
C(UNIT)[T.R120]  1448.8422    216.797      6.683      0.000      1023.916  1873.768
C(UNIT)[T.R121]  1406.6968    216.193      6.507      0.000       982.954  1830.440
C(UNIT)[T.R122]  2518.9734    214.735     11.731      0.000      2098.088  2939.859
C(UNIT)[T.R123]  1578.3821    215.022      7.341      0.000      1156.934  1999.830
C(UNIT)[T.R124]   593.1490    217.730      2.724      0.006       166.393  1019.905
C(UNIT)[T.R126]  1818.1799    213.346      8.522      0.000      1400.017  2236.343
C(UNIT)[T.R127]  4758.8896    213.346     22.306      0.000      4340.726  5177.053
C(UNIT)[T.R137]  2404.3669    213.343     11.270      0.000      1986.211  2822.523
C(UNIT)[T.R139]  2493.5545    213.619     11.673      0.000      2074.858  2912.251
C(UNIT)[T.R163]  3294.6262    213.346     15.443      0.000      2876.463  3712.789
C(UNIT)[T.R172]  1860.6638    213.346      8.721      0.000      1442.501  2278.827
C(UNIT)[T.R179]  6741.4380    213.346     31.599      0.000      6323.275  7159.601
C(UNIT)[T.R181]  1717.0979    215.309      7.975      0.000      1295.088  2139.108
C(UNIT)[T.R183]   685.0110    219.346      3.123      0.002       255.088  1114.934
C(UNIT)[T.R184]   939.7659    218.048      4.310      0.000       512.387  1367.144
C(UNIT)[T.R186]  1039.3998    214.735      4.840      0.000       618.515  1460.285
C(UNIT)[T.R188]  2294.0689    213.619     10.739      0.000      1875.372  2712.766
C(UNIT)[T.R189]  1349.9518    215.896      6.253      0.000       926.792  1773.112
C(UNIT)[T.R194]  1956.8246    215.310      9.088      0.000      1534.812  2378.837
C(UNIT)[T.R196]  1291.5662    214.171      6.031      0.000       871.786  1711.346
C(UNIT)[T.R198]  2076.8197    213.893      9.710      0.000      1657.585  2496.054
C(UNIT)[T.R199]   679.4824    215.311      3.156      0.002       257.469  1101.495
C(UNIT)[T.R200]  1006.2425    214.449      4.692      0.000       585.918  1426.567
C(UNIT)[T.R202]  2190.3467    213.893     10.240      0.000      1771.112  2609.581
C(UNIT)[T.R203]  1720.4146    216.496      7.947      0.000      1296.079  2144.750
C(UNIT)[T.R204]  1422.1638    213.346      6.666      0.000      1004.001  1840.327
C(UNIT)[T.R205]  1472.4970    214.449      6.866      0.000      1052.173  1892.821
C(UNIT)[T.R207]  1971.3824    213.619      9.229      0.000      1552.685  2390.080
C(UNIT)[T.R208]  2471.5842    214.448     11.525      0.000      2051.262  2891.906
C(UNIT)[T.R209]   728.8076    218.690      3.333      0.001       300.170  1157.445
C(UNIT)[T.R210]   495.8174    215.897      2.297      0.022        72.655   918.980
C(UNIT)[T.R211]  2379.5939    213.346     11.154      0.000      1961.431  2797.757
C(UNIT)[T.R212]  1660.4325    213.619      7.773      0.000      1241.736  2079.129
C(UNIT)[T.R213]  1116.7008    215.601      5.179      0.000       694.119  1539.283
C(UNIT)[T.R214]   605.8473    219.018      2.766      0.006       176.567  1035.127
C(UNIT)[T.R215]  1568.6746    213.895      7.334      0.000      1149.436  1987.913
C(UNIT)[T.R216]   738.0823    213.894      3.451      0.001       318.846  1157.318
C(UNIT)[T.R217]   941.6006    218.691      4.306      0.000       512.962  1370.239
C(UNIT)[T.R218]  1950.2314    213.615      9.130      0.000      1531.542  2368.921
C(UNIT)[T.R219]  1230.6300    213.891      5.754      0.000       811.399  1649.861
C(UNIT)[T.R220]  1454.3197    213.346      6.817      0.000      1036.157  1872.483
C(UNIT)[T.R221]  1350.6547    219.021      6.167      0.000       921.370  1779.940
C(UNIT)[T.R223]  2089.6889    213.615      9.783      0.000      1670.999  2508.379
C(UNIT)[T.R224]   688.5512    216.194      3.185      0.001       264.807  1112.296
C(UNIT)[T.R225]   544.5445    214.736      2.536      0.011       123.657   965.432
C(UNIT)[T.R226]   661.3167    218.043      3.033      0.002       233.947  1088.686
C(UNIT)[T.R227]  1073.5832    213.346      5.032      0.000       655.420  1491.746
C(UNIT)[T.R228]  1086.3305    218.375      4.975      0.000       658.311  1514.350
C(UNIT)[T.R229]   517.8968    217.730      2.379      0.017        91.142   944.651
C(UNIT)[T.R230]   477.5627    216.494      2.206      0.027        53.229   901.896
C(UNIT)[T.R231]   935.8538    214.735      4.358      0.000       514.969  1356.739
C(UNIT)[T.R232]   970.6727    217.416      4.465      0.000       544.533  1396.812
C(UNIT)[T.R233]  1046.9559    219.684      4.766      0.000       616.370  1477.542
C(UNIT)[T.R234]   252.3328    218.693      1.154      0.249      -176.310   680.975
C(UNIT)[T.R235]  2546.1543    213.619     11.919      0.000      2127.457  2964.852
C(UNIT)[T.R236]  1489.5521    214.447      6.946      0.000      1069.231  1909.873
C(UNIT)[T.R237]   598.0644    218.365      2.739      0.006       170.064  1026.065
C(UNIT)[T.R238]  2072.2484    213.615      9.701      0.000      1653.559  2490.938
C(UNIT)[T.R239]   870.7445    213.346      4.081      0.000       452.581  1288.908
C(UNIT)[T.R240]  2629.5499    214.171     12.278      0.000      2209.771  3049.329
C(UNIT)[T.R242]   511.9562    215.602      2.375      0.018        89.372   934.541
C(UNIT)[T.R243]  1327.9865    217.104      6.117      0.000       902.458  1753.515
C(UNIT)[T.R244]  1568.7820    217.112      7.226      0.000      1143.239  1994.325
C(UNIT)[T.R246]   628.1284    218.369      2.876      0.004       200.120  1056.136
C(UNIT)[T.R247]    76.9454    220.364      0.349      0.727      -354.973   508.864
C(UNIT)[T.R248]  3075.8842    213.619     14.399      0.000      2657.187  3494.581
C(UNIT)[T.R249]  1321.9826    215.020      6.148      0.000       900.539  1743.426
C(UNIT)[T.R250]   936.2667    215.602      4.343      0.000       513.683  1358.850
C(UNIT)[T.R251]  1245.5435    214.170      5.816      0.000       825.765  1665.322
C(UNIT)[T.R252]   929.8482    213.893      4.347      0.000       510.613  1349.083
C(UNIT)[T.R253]   694.6848    217.427      3.195      0.001       268.523  1120.846
C(UNIT)[T.R254]  2559.0720    213.617     11.980      0.000      2140.379  2977.765
C(UNIT)[T.R255]   723.0479    214.448      3.372      0.001       302.725  1143.370
C(UNIT)[T.R256]  1034.7154    213.895      4.837      0.000       615.477  1453.954
C(UNIT)[T.R257]  1857.9165    213.346      8.708      0.000      1439.753  2276.080
C(UNIT)[T.R258]  1492.6751    214.171      6.970      0.000      1072.896  1912.454
C(UNIT)[T.R259]   892.6774    215.020      4.152      0.000       471.234  1314.121
C(UNIT)[T.R260]  1029.6156    222.857      4.620      0.000       592.810  1466.421
C(UNIT)[T.R261]  1518.3126    215.893      7.033      0.000      1095.158  1941.467
C(UNIT)[T.R262]   387.3034    220.364      1.758      0.079       -44.615   819.221
C(UNIT)[T.R263]    93.0966    215.604      0.432      0.666      -329.492   515.685
C(UNIT)[T.R264]   445.2666    213.620      2.084      0.037        26.567   863.967
C(UNIT)[T.R265]   815.0510    217.730      3.743      0.000       388.295  1241.807
C(UNIT)[T.R266]   871.8143    213.615      4.081      0.000       453.125  1290.504
C(UNIT)[T.R269]   852.4842    213.895      3.986      0.000       433.247  1271.722
C(UNIT)[T.R270]   429.8884    218.373      1.969      0.049         1.874   857.903
C(UNIT)[T.R271]   300.8644    218.049      1.380      0.168      -126.516   728.244
C(UNIT)[T.R273]  1308.3912    218.701      5.983      0.000       879.732  1737.050
C(UNIT)[T.R274]   907.0552    217.420      4.172      0.000       480.908  1333.202
C(UNIT)[T.R275]   846.7931    215.894      3.922      0.000       423.636  1269.950
C(UNIT)[T.R276]  1380.4541    213.346      6.470      0.000       962.291  1798.617
C(UNIT)[T.R277]   357.0734    221.409      1.613      0.107       -76.892   791.039
C(UNIT)[T.R278]   311.6851    217.731      1.432      0.152      -115.072   738.443
C(UNIT)[T.R279]   715.1286    215.305      3.321      0.001       293.126  1137.131
C(UNIT)[T.R280]   573.9237    220.711      2.600      0.009       141.327  1006.521
C(UNIT)[T.R281]  1242.6690    215.022      5.779      0.000       821.221  1664.117
C(UNIT)[T.R282]  1549.1669    213.894      7.243      0.000      1129.931  1968.403
C(UNIT)[T.R284]   738.2450    213.893      3.451      0.001       319.010  1157.480
C(UNIT)[T.R285]   502.6042    219.019      2.295      0.022        73.323   931.885
C(UNIT)[T.R287]   476.9266    219.350      2.174      0.030        46.997   906.856
C(UNIT)[T.R291]  1773.6853    213.346      8.314      0.000      1355.522  2191.848
C(UNIT)[T.R294]   889.7336    215.896      4.121      0.000       466.573  1312.894
C(UNIT)[T.R295]   525.4130    230.277      2.282      0.023        74.065   976.761
C(UNIT)[T.R300]  2182.7498    213.346     10.231      0.000      1764.587  2600.913
C(UNIT)[T.R303]  1188.4383    215.022      5.527      0.000       766.991  1609.885
C(UNIT)[T.R304]  1047.9327    213.895      4.899      0.000       628.695  1467.171
C(UNIT)[T.R307]   250.3512    219.346      1.141      0.254      -179.571   680.273
C(UNIT)[T.R308]   717.4721    217.103      3.305      0.001       291.947  1142.997
C(UNIT)[T.R309]   749.4458    216.799      3.457      0.001       324.515  1174.376
C(UNIT)[T.R310]  1210.2727    218.044      5.551      0.000       782.903  1637.642
C(UNIT)[T.R311]   333.5250    216.497      1.541      0.123       -90.814   757.864
C(UNIT)[T.R312]   287.8045    214.171      1.344      0.179      -131.974   707.583
C(UNIT)[T.R313]   -50.9103    219.680     -0.232      0.817      -481.487   379.667
C(UNIT)[T.R318]   495.4045    214.451      2.310      0.021        75.076   915.733
C(UNIT)[T.R319]  1295.3637    215.311      6.016      0.000       873.350  1717.377
C(UNIT)[T.R321]  1045.3466    213.346      4.900      0.000       627.183  1463.510
C(UNIT)[T.R322]  1728.3271    215.313      8.027      0.000      1306.309  2150.345
C(UNIT)[T.R323]  1195.2084    217.418      5.497      0.000       769.065  1621.351
C(UNIT)[T.R325]   261.4527    216.491      1.208      0.227      -162.875   685.780
C(UNIT)[T.R330]   924.5944    215.898      4.283      0.000       501.430  1347.759
C(UNIT)[T.R335]   270.1720    220.023      1.228      0.219      -161.077   701.421
C(UNIT)[T.R336]   -92.0995    220.020     -0.419      0.676      -523.342   339.143
C(UNIT)[T.R337]   -31.6541    218.691     -0.145      0.885      -460.293   396.985
C(UNIT)[T.R338]  -155.3851    216.797     -0.717      0.474      -580.311   269.541
C(UNIT)[T.R341]   434.8734    214.172      2.030      0.042        15.092   854.655

In [8]:
entries_rain = weather_subway[weather_subway['rain']==1].ENTRIESn_hourly
entries_norain = weather_subway[weather_subway['rain']==0].ENTRIESn_hourly

In [9]:
scipy.stats.shapiro(entries_norain)
scipy.stats.shapiro(entries_rain)

C:\Users\Saad Khalid\Anaconda\lib\site-packages\scipy\stats\morestats.py:995: UserWarning: p-value may not be accurate for N > 5000.
  warnings.warn("p-value may not be accurate for N > 5000.")

(0.5938820838928223, 0.0)

In [10]:
n_one = len(entries_norain)
n_two = len(entries_rain)

scipy.stats.mannwhitneyu(entries_norain, entries_rain)

(153635120.5, nan)

In [13]:
ggplot(aes(x='ENTRIESn_hourly', color='rain', fill='rain'), data = weather_subway) + \
    geom_density() + \
    xlab("Hourly passenger entries") + \
    ylab("Frequency") + \
    ggtitle("Hourly passenger entries (weekdays and weekends)") + \
    theme_seaborn()

In [10]:
def STD(n1, n2):
    return np.sqrt((n1*n2)*(n1+n2+1)/12)

In [11]:
STD(n_one, n_two)

1061310.9607933012

In [12]:
z_score = (scipy.stats.mannwhitneyu(entries_norain, entries_rain)[0]-(n_one*n_two/2))/STD(n_one, n_two)
print(z_score)

-4.54541569645

In [48]:
p_values = 1 - scipy.stats.norm.sf(z_score)
print(p_values)
print(p_values * 2)

2.74134693568e-06
5.48269387135e-06

In [16]:
weather_subway.DATEn

0     05-01-11
1     05-01-11
2     05-01-11
3     05-01-11
4     05-01-11
5     05-02-11
6     05-02-11
7     05-02-11
8     05-02-11
9     05-02-11
10    05-02-11
11    05-03-11
12    05-03-11
13    05-03-11
14    05-03-11
...
42634    05-29-11
42635    05-29-11
42636    05-29-11
42637    05-30-11
42638    05-30-11
42639    05-30-11
42640    05-30-11
42641    05-30-11
42642    05-30-11
42643    05-31-11
42644    05-31-11
42645    05-31-11
42646    05-31-11
42647    05-31-11
42648    05-31-11
Name: DATEn, Length: 42649, dtype: object